### PR TITLE
Run docker build on PR

### PR DESCRIPTION
**Pull request by dati18**

### CODE REVIEW

**Comment by m90** [comment]
Over in `api` we also build the image on Pull Requests, but don't push them, I guess we want the same here: https://github.com/wbstack/api/blob/184cdd4f063a9ed70ac948be8ce6c1d79e11e420/.github/workflows/docker.build.yml#L55

**Comment by dati18** [comment]
@m90 please check again

**Comment by m90** [comment]
I think the additional trigger is still needed. See the action definition for API as a reference

**Comment by dati18** [comment]
can you elaborate @m90 ?

**Comment by m90** [comment]
Right now, only pushes to main will trigger a build at all:

```
on:
  push:
    branches:
    - main
```

Compare this with API which has an additional `pull_request` trigger:

```
on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
```

I don't think the tags are needed for `ui`, but we'll definitely need the `pull_request` trigger that kicks off this workflow, telling us if the image builds correctly. We then skip pushing the image to the image registry using the condition in `push`

**Review by tarrow — APPROVED** [review]

**Pull request merged**
